version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cinema-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: FillRouge
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: cinema-app
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/FillRouge
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - mysql

volumes:
  mysql_data: